var TEXT_PRELOADER_CONTINUE = "DÉMARRER";
var LANGUAGE = "LANGUE";
var FRENCH = "FRANÇAIS";
var ENGLISH = "ANGLAIS";
var TEXT_MULTIPLIER = "x";
var TEXT_SCORE = "SCORE";
var TEXT_LEVEL_SCORE = "LEVEL SCORE";
var TEXT_TOTAL = "SCORE TOTAL";
var TEXT_GOAL = "BUT!";
var TEXT_ARE_SURE = "ES-TU CERTAIN DE VOULOIR QUITTER LE JEU?";
var TEXT_CONFIRM_DELETE = "TOUTES LES SAUVEGARDES SERONT SUPPRIMÉES! ES-TU SÛR?";
var TEXT_SAVED = "ARRÊTÉ!";
var TEXT_MISSED = "RÂTÉ!";
var TEXT_HELP = "FAIT GLISSER POUR FRAPPER LE BALLON";
var TEXT_HELP_KEEPER = "TAPE L'ÉCRAN POUR LAISSER L'ADVERSAIRE TIRER";
var TEXT_WIN = "VICTOIRE";
var TEXT_LOSE = "DÉFAITE";
var TEXT_CREDITS_DEVELOPED = "DÉVELOPPÉ PAR";
var TEXT_VS = "VS";
var TEXT_MATCH = "MATCH";
var TEXT_SELECT_TEAM = "SÉLECTIONNEZ VOTRE ÉQUIPE";
var TEXT_MATCHES = "MATCHS";
var TEXT_ERR_LS = "VOTRE NAVIGATEUR WEB NE PREND PAS EN CHARGE LE STOCKAGE LOCAL. SI VOUS UTILISEZ SAFARI, CELA PEUT ÊTRE LIÉ À LA NAVIGATION PRIVÉE. EN CONSÉQUENCE, CERTAINES INFORMATIONS PEUVENT NE PAS ÊTRE ENREGISTRÉES OU CERTAINES FONCTIONNALITÉS PEUVENT NE PAS ÊTRE DISPONIBLES.";


var TEXT_TEAM = new Array();
TEXT_TEAM[0] = "RUSSIE";
TEXT_TEAM[1] = "JAPON";
TEXT_TEAM[2] = "L'IRAN";
TEXT_TEAM[3] = "BRÉSIL";
TEXT_TEAM[4] = "MEXIQUE";
TEXT_TEAM[5] = "BELGIQUE";
TEXT_TEAM[6] = "CORÉE DU SUD";
TEXT_TEAM[7] = "ARABIE SAOUDITE";
TEXT_TEAM[8] = "ALLEMAGNE";
TEXT_TEAM[9] = "ANGLETERRE";
TEXT_TEAM[10] = "ESPAGNE";
TEXT_TEAM[11] = "NIGERIA";
TEXT_TEAM[12] = "COSTA RICA";
TEXT_TEAM[13] = "POLOGNE";
TEXT_TEAM[14] = "EGYPTE";
TEXT_TEAM[15] = "SERBIE";
TEXT_TEAM[16] = "ISLANDE";
TEXT_TEAM[17] = "FRANCE";
TEXT_TEAM[18] = "LE PORTUGAL";
TEXT_TEAM[19] = "URUGUAY";
TEXT_TEAM[20] = "ARGENTINE";
TEXT_TEAM[21] = "COLOMBIE";
TEXT_TEAM[22] = "PANAMA";
TEXT_TEAM[23] = "SÉNÉGAL";
TEXT_TEAM[24] = "MAROC";
TEXT_TEAM[25] = "TUNISIE";
TEXT_TEAM[26] = "SUISSE";
TEXT_TEAM[27] = "CROATIE";
TEXT_TEAM[28] = "SUÈDE";
TEXT_TEAM[29] = "DANEMARK";
TEXT_TEAM[30] = "AUSTRALIE";
TEXT_TEAM[31] = "PÉROU";

var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Félicitations!";
var TEXT_SHARE_MSG1 = "Vous avez collecté <strong>";
var TEXT_SHARE_MSG2 = " points</strong> !<br><br>Partagez votre score avec vos amis!";
var TEXT_SHARE_SHARE1 = "Mon score est";
var TEXT_SHARE_SHARE2 = " points! Pouvez-vous faire mieux ??";


///////////// GAME MULTIPLAYER TEXT
var TEXT_WAIT_OPPONENT = " EN ATTENDANT L'ADVERSANT...";
var TEXT_OPPONENT_LEFT = "ADVERSAIRE À GAUCHE!";
var TEXT_PLAYER_DISCONNECTED = "VOUS AVEZ QUITTÉ!";
var TEXT_REMATCH = "tu veux le rematch ?";
var TEXT_WAIT_STRIKER = "VOTRE ADVERSAIRE TONNE DES PIEDS";
var TEXT_GET_READY = "SOIS PRÊT!";
var TEXT_WAIT_GOALKEEPER = "VOTRE ADVERSAIRE EST PRÊT À SAUVER!";

///////////// LOGIN ROOM SYSTEM TEXT
var TEXT_NETWORK_CONNECTING = "de liaison...";
var TEXT_WRONG_PASSWORD = "Faux mot de passe!";
var TEXT_ROOM_IS_FULL = "La chambre est pleine!";
var TEXT_FIND_OPPONENT = "trouver un adversaire...";
var TEXT_CONNECT_TO_LOBBY = "se connecter au lobby...";
var TEXT_ROOM_DOESNT_EXIST = "La chambre n'existe pas!";
var TEXT_WAITING_FOR_OPPONENT_IN_ROOM = "en attendant l'adversaire dans la chambre: ";

var TEXT_PLAYER_1 = "JOUEUR1";
var TEXT_PLAYER_2 = "JOUEUR2";
var TEXT_CPU = "CPU";










