var TEXT_PRELOADER_CONTINUE = "START";
var LANGUAGE = "LANGUAGE";
var FRENCH = "FRENCH";
var ENGLISH = "ENGLISH";
var TEXT_MULTIPLIER = "x";
var TEXT_SCORE = "SCORE";
var TEXT_LEVEL_SCORE = "LEVEL SCORE";
var TEXT_TOTAL = "TOTAL SCORE";
var TEXT_GOAL = "GOAL!";
var TEXT_ARE_SURE = "ARE YOU SURE YOU WANT TO EXIT THE GAME?";
var TEXT_CONFIRM_DELETE = "ALL SAVING WILL BE DELETED! ARE YOU SURE?";
var TEXT_SAVED = "SAVED!";
var TEXT_MISSED = "MISS!";
var TEXT_HELP = "SWIPE TO KICK THE BALL";
var TEXT_HELP_KEEPER = "TAP THE SCREEN TO LET THE OPPONENT KICK";
var TEXT_WIN = "YOU WON";
var TEXT_LOSE = "YOU LOSE";
var TEXT_CREDITS_DEVELOPED = "DEVELOPED BY";
var TEXT_VS = "VS";
var TEXT_MATCH = "MATCH";
var TEXT_SELECT_TEAM = "SELECT YOUR TEAM";
var TEXT_MATCHES = "MATCHES";
var TEXT_ERR_LS = "YOUR WEB BROWSER DOES NOT SUPPORT LOCAL STORAGE. IF YOU'RE USING SAFARI, IT MAY BE RELATED TO PRIVATE BROWSING. AS A RESULT, SOME INFO MAY NOT BE SAVED OR SOME FEATURES MAY NOT BE AVAILABLE.";

var TEXT_TEAM = new Array();
TEXT_TEAM[0] = "RUSSIA";
TEXT_TEAM[1] = "JAPAN";
TEXT_TEAM[2] = "IRAN";
TEXT_TEAM[3] = "BRAZIL";
TEXT_TEAM[4] = "MEXICO";
TEXT_TEAM[5] = "BELGIUM";
TEXT_TEAM[6] = "SOUTH KOREA";
TEXT_TEAM[7] = "SAUDI ARABIA";
TEXT_TEAM[8] = "GERMANY";
TEXT_TEAM[9] = "ENGLAND";
TEXT_TEAM[10] = "SPAIN";
TEXT_TEAM[11] = "NIGERIA";
TEXT_TEAM[12] = "COSTA RICA";
TEXT_TEAM[13] = "POLAND";
TEXT_TEAM[14] = "EGYPT";
TEXT_TEAM[15] = "SERBIA";
TEXT_TEAM[16] = "ICELAND";
TEXT_TEAM[17] = "FRANCE";
TEXT_TEAM[18] = "PORTUGAL";
TEXT_TEAM[19] = "URUGUAY";
TEXT_TEAM[20] = "ARGENTINA";
TEXT_TEAM[21] = "COLOMBIA";
TEXT_TEAM[22] = "PANAMA";
TEXT_TEAM[23] = "SENEGAL";
TEXT_TEAM[24] = "MOROCCO";
TEXT_TEAM[25] = "TUNISIA";
TEXT_TEAM[26] = "SWITZERLAND";
TEXT_TEAM[27] = "CROATIA";
TEXT_TEAM[28] = "SWEDEN";
TEXT_TEAM[29] = "DENMARK";
TEXT_TEAM[30] = "AUSTRALIA";
TEXT_TEAM[31] = "PERU";


var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Congratulations!";
var TEXT_SHARE_MSG1 = "You collected <strong>";
var TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1 = "My score is ";
var TEXT_SHARE_SHARE2 = " points! Can you do better?";

///////////// GAME MULTIPLAYER TEXT
var TEXT_WAIT_OPPONENT = "WAITING OPPONENT...";
var TEXT_OPPONENT_LEFT = "OPPONENT LEFT!";
var TEXT_PLAYER_DISCONNECTED = "YOU LEFT!";
var TEXT_REMATCH = "do you want the re-match?";
var TEXT_WAIT_STRIKER = "YOUR OPPONENT IS KICKING";
var TEXT_GET_READY = "GET READY!";
var TEXT_WAIT_GOALKEEPER = "YOUR OPPONENT IS READY TO SAVE!";

///////////// LOGIN ROOM SYSTEM TEXT
var TEXT_NETWORK_CONNECTING = "connecting...";
var TEXT_WRONG_PASSWORD = "Wrong Password!";
var TEXT_ROOM_IS_FULL = "Room is full!";
var TEXT_FIND_OPPONENT = "finding opponent...";
var TEXT_CONNECT_TO_LOBBY = "Connect to lobby...";
var TEXT_ROOM_DOESNT_EXIST = "Room doesn't exist!";
var TEXT_WAITING_FOR_OPPONENT_IN_ROOM = "waiting for opponent in room: ";

var TEXT_PLAYER_1 = "PLAYER1";
var TEXT_PLAYER_2 = "PLAYER2";
var TEXT_CPU = "CPU";